In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [21]:
def conv2d(input_matrix, kernel,same=False):
    output = np.zeros([input_matrix.shape[0]+kernel.shape[0]-1, input_matrix.shape[1]+kernel.shape[1]-1])
    #Rotating kernel by 180
    rotated_kernel = np.zeros(kernel.shape)
    for i in range(kernel.shape[0]):
        for j in range(kernel.shape[1]):
            rotated_kernel[i][j] = kernel[kernel.shape[0]-1-i][kernel.shape[1]-1-j]
    print(rotated_kernel)

    padded_img = np.zeros([input_matrix.shape[0] + 4, input_matrix.shape[1] + 4])
    padded_img[2:2+input_matrix.shape[0], 2:2+input_matrix.shape[1]] = input_matrix
    
    for centre_row in range(output.shape[0]):
        for centre_col in range(output.shape[1]):
            padding_submat = padded_img[centre_row:kernel.shape[0]+centre_row, centre_col:kernel.shape[1]+centre_col]
            product = rotated_kernel.flatten().dot(padding_submat.flatten())
            output[centre_row][centre_col] = product
            
    if same==True:
        limit_row=output.shape[0]-input_matrix.shape[0]
        limit_col=output.shape[1]-input_matrix.shape[1]
        output=output[limit_row-1:output.shape[0]-limit_row+1,limit_col-1:output.shape[1]-limit_col+1]
        
    return output

In [22]:
kernel=np.array([[0,1,0],[1,-4,1],[0,1,0]])
input_img=np.array([[6,7],[8,9]])
conv_output=conv2d(input_img,kernel)

[[ 0.  1.  0.]
 [ 1. -4.  1.]
 [ 0.  1.  0.]]


In [23]:
from tabulate import tabulate
table = tabulate(conv_output, tablefmt="fancy_grid")
print(table)

╒═══╤═════╤═════╤═══╕
│ 0 │   6 │   7 │ 0 │
├───┼─────┼─────┼───┤
│ 6 │  -9 │ -13 │ 7 │
├───┼─────┼─────┼───┤
│ 8 │ -17 │ -21 │ 9 │
├───┼─────┼─────┼───┤
│ 0 │   8 │   9 │ 0 │
╘═══╧═════╧═════╧═══╛
